version: '2'
services:
  backend:
    hostname: python
    container_name: dollar_backend
    working_dir: /www/
    build: backend
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./backend:/www/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command: bash -c "python manage.py runserver 0.0.0.0:8000 && service cron start"
